# Generated by Django 4.2.7 on 2026-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_closed', 'Registration Closed'), ('in_progress', 'In Progress'), ('scoring_closed', 'Scoring Closed'), ('results_published', 'Results Published'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
    ]
