# Generated by Django 4.2.7 on 2026-01-19 14:35

from django.db import migrations


def migrate_event_status(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    # Set status based on is_published field
    # Events that are published should be in 'published' status
    # Events that are not published should remain in 'draft' status
    Event.objects.filter(is_published=True).update(status='published')
    # Events with is_published=False remain as 'draft' (default)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_event_status_field'),
    ]

    operations = [
        migrations.RunPython(migrate_event_status),
    ]
