# Generated by Django 4.2.7 on 2026-01-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_migrate_existing_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_published',
        ),
    ]
