# Generated by Django 4.2.7 on 2026-03-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_event_defin_category_1d051f_idx_event_defin_categor_2ba931_idx_and_more'),
        ('events', '0009_remove_is_published_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to='catalog.eventdefinition'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to='catalog.eventvariant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('dance', 'Dance'), ('music', 'Music'), ('theatre', 'Theatre'), ('literary', 'Literary'), ('visual_arts', 'Visual Arts'), ('traditional_arts', 'Traditional Arts')], max_length=20),
        ),
    ]
