# Generated by Django 4.2.7 on 2026-03-15 21:24

from django.db import migrations


CATEGORY_MAPPING = {
    "DANCE": "dance",
    "MUSIC": "music",
    "THEATRE": "theatre",
    "LITERARY": "literary",
    "FINE_ARTS": "visual_arts",
    "TRADITIONAL_ARTS": "traditional_arts",
}


def _canonical_name(event_definition_name, event_variant_name=None, max_length=100):
    base_name = (event_definition_name or "").strip()
    variant_name = (event_variant_name or "").strip()
    value = f"{base_name} - {variant_name}" if variant_name else base_name
    return value[:max_length]


def backfill_event_catalog_alignment(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    queryset = Event.objects.select_related(
        "event_definition",
        "event_definition__category",
        "event_variant",
    )

    for event in queryset.iterator():
        fields_to_update = []
        event_definition = getattr(event, "event_definition", None)
        event_variant = getattr(event, "event_variant", None)

        if event_definition is None:
            if event_variant is not None:
                event.event_variant = None
                fields_to_update.append("event_variant")
        else:
            if event_variant is not None and getattr(event_variant, "event_id", None) != event_definition.id:
                event.event_variant = None
                event_variant = None
                fields_to_update.append("event_variant")

            canonical_name = _canonical_name(
                getattr(event_definition, "event_name", ""),
                getattr(event_variant, "variant_name", None) if event_variant is not None else None,
                max_length=100,
            )
            if event.name != canonical_name:
                event.name = canonical_name
                fields_to_update.append("name")

            category_name = getattr(getattr(event_definition, "category", None), "category_name", None)
            mapped_category = CATEGORY_MAPPING.get((category_name or "").strip().upper())
            if mapped_category is not None and event.category != mapped_category:
                event.category = mapped_category
                fields_to_update.append("category")

        if fields_to_update:
            event.save(update_fields=list(dict.fromkeys(fields_to_update)))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_event_event_definition_event_event_variant_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_event_catalog_alignment, noop_reverse),
    ]
