# Generated by Django 4.2.7 on 2026-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_backfill_event_catalog_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='group_leader_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='group_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
