# Generated by Django 4.2.7 on 2026-03-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventregistration_group_leader_name_and_more'),
        ('users', '0016_schoolgroupentry_schoolgroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='school_group_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='users.schoolgroupentry'),
        ),
    ]
