# Generated by Django 4.2.7 on 2026-03-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'art_categories',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(max_length=10, unique=True)),
                ('level_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='ParticipationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'participation_types',
            },
        ),
        migrations.CreateModel(
            name='EventDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.artcategory')),
                ('participation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.participationtype')),
            ],
            options={
                'db_table': 'event_definitions',
            },
        ),
        migrations.CreateModel(
            name='EventVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.eventdefinition')),
            ],
            options={
                'db_table': 'event_variants',
                'unique_together': {('event', 'variant_name')},
            },
        ),
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_eligibility', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('MIXED', 'Mixed')], max_length=10)),
                ('min_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalog.eventdefinition')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_rules', to='catalog.level')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='catalog.eventvariant')),
            ],
            options={
                'db_table': 'event_rules',
            },
        ),
        migrations.AddIndex(
            model_name='eventdefinition',
            index=models.Index(fields=['category'], name='event_defin_categor_2ba931_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdefinition',
            index=models.Index(fields=['participation_type'], name='event_defin_partici_c7f5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvariant',
            index=models.Index(fields=['event'], name='event_varia_event_i_2ebac5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrule',
            index=models.Index(fields=['event'], name='event_rules_event_i_38b5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrule',
            index=models.Index(fields=['variant'], name='event_rules_variant_c35c93_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrule',
            index=models.Index(fields=['level'], name='event_rules_level_i_82cd28_idx'),
        ),
    ]
