# Generated by Django 4.2.7 on 2026-03-12 00:00

from django.db import migrations


def seed_static(apps, schema_editor):
    ArtCategory = apps.get_model('catalog', 'ArtCategory')
    Level = apps.get_model('catalog', 'Level')
    ParticipationType = apps.get_model('catalog', 'ParticipationType')

    for name in [
        'LITERARY',
        'MUSIC',
        'DANCE',
        'THEATRE',
        'FINE_ARTS',
        'TRADITIONAL_ARTS',
    ]:
        ArtCategory.objects.get_or_create(category_name=name)

    for code, display in [
        ('LP', 'Lower Primary'),
        ('UP', 'Upper Primary'),
        ('HS', 'High School'),
        ('HSS', 'Higher Secondary School'),
    ]:
        Level.objects.get_or_create(level_code=code, defaults={'level_name': display})

    for type_name in ['INDIVIDUAL', 'GROUP']:
        ParticipationType.objects.get_or_create(type_name=type_name)


def unseed_static(apps, schema_editor):
    # Keep data on reverse migrations (safe no-op)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_static, unseed_static),
    ]
