# Generated by Django 4.2.7 on 2026-03-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_static_data'),
    ]

    operations = [
        # No-op: initial migration already uses the final index names.
    ]
