# Generated by Django 4.2.7 on 2025-12-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_add_volunteers_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire / Smoke'), ('security', 'Security / Safety'), ('other', 'Other')], max_length=20)),
                ('person_role', models.CharField(blank=True, choices=[('participant', 'Participant'), ('judge', 'Judge'), ('volunteer', 'Volunteer'), ('staff', 'Staff'), ('public', 'Public Visitor')], max_length=20)),
                ('person_id_value', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('cause_type', models.CharField(blank=True, max_length=20)),
                ('cause_description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_from', models.CharField(choices=[('public_button', 'Public Button'), ('volunteer', 'Volunteer')], default='public_button', max_length=20)),
                ('requires_schedule_adjustment', models.BooleanField(default=False)),
                ('schedule_adjusted', models.BooleanField(default=False)),
                ('hospital_notified', models.BooleanField(default=False)),
                ('hospital_reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='events.event')),
                ('person_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_as_subject', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='events.venue')),
            ],
        ),
    ]
