# Generated by Django 4.2.7 on 2026-02-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('created', 'Created'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('escalated', 'Escalated')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'endpoint'], name='emergencies_key_3181ce_idx'), models.Index(fields=['expires_at'], name='emergencies_expires_3760c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('notified', 'Notified'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('timeout', 'Timeout'), ('on_site', 'On Site'), ('completed', 'Completed')], default='notified', max_length=20)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('on_site_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='emergencies.emergency')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notified_at'],
                'unique_together': {('emergency', 'volunteer')},
            },
        ),
    ]
