# Generated by Django 4.2.7 on 2025-10-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_add_anomaly_detection_fields'),
        ('scores', '0002_score_criteria_scores_and_more'),
    ]

    operations = [
    ]
