# Generated by Django 4.2.7 on 2025-12-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0003_merge_20251030_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecheckRequest',
            fields=[
                ('recheck_request_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the recheck request', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Participant's full name at time of request", max_length=255)),
                ('category', models.CharField(help_text='Event category at time of request', max_length=50)),
                ('event_name', models.CharField(help_text='Event name at time of request', max_length=100)),
                ('chest_number', models.CharField(help_text="Participant's chest number at time of request", max_length=20)),
                ('final_score', models.DecimalField(decimal_places=2, help_text='Final score at time of request', max_digits=6)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', help_text='Current status of the recheck request', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the request was accepted by volunteer', null=True)),
                ('assigned_volunteer', models.ForeignKey(help_text='Volunteer assigned to process this request', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recheck_requests', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(help_text='The participant requesting the re-check', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(help_text='The result being requested for re-check', on_delete=django.db.models.deletion.CASCADE, to='scores.result')),
            ],
            options={
                'db_table': 'scores_recheck_request',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['assigned_volunteer', 'status'], name='scores_rech_assigne_7cd9bb_idx'), models.Index(fields=['participant', 'result'], name='scores_rech_partici_c56b46_idx'), models.Index(fields=['status'], name='scores_rech_status_a9e672_idx')],
                'unique_together': {('result', 'participant')},
            },
        ),
    ]
