# Generated by Django 4.2.7 on 2025-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_recheckrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheckrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason provided by the participant for the re-check request', null=True),
        ),
    ]
