# Generated by Django 4.2.7 on 2026-01-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_razorpaypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recheckrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the recheck request', max_length=10),
        ),
    ]
