# Generated by Django 4.2.7 on 2025-10-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_volunteers_field'),
        ('users', '0009_user_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(blank=True, help_text='Admin-issued ID for registration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('judge', 'Judge'), ('admin', 'Admin'), ('volunteer', 'Volunteer'), ('school', 'School')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdminIssuedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('role', models.CharField(choices=[('volunteer', 'Volunteer'), ('judge', 'Judge')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_ids', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_with_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Issued ID',
                'verbose_name_plural': 'Admin Issued IDs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolVolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_volunteer_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(limit_choices_to={'role': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_volunteer', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School-Volunteer Assignment',
                'verbose_name_plural': 'School-Volunteer Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('school', 'volunteer')},
            },
        ),
        migrations.CreateModel(
            name='SchoolStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('total_gold', models.PositiveIntegerField(default=0)),
                ('total_silver', models.PositiveIntegerField(default=0)),
                ('total_bronze', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(limit_choices_to={'role': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Standing',
                'verbose_name_plural': 'School Standings',
                'ordering': ['-total_points', '-total_gold', '-total_silver'],
                'unique_together': {('school',)},
            },
        ),
        migrations.CreateModel(
            name='SchoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(help_text='School-assigned participant ID', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_class', models.PositiveSmallIntegerField(help_text='Class 1-12')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by_volunteer', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('events', models.ManyToManyField(related_name='school_participant_events', to='events.event')),
                ('school', models.ForeignKey(limit_choices_to={'role': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_participants', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_school_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Participant',
                'verbose_name_plural': 'School Participants',
                'ordering': ['-submitted_at'],
                'unique_together': {('school', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='IDSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_requests', to='users.adminissuedid')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_signup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Signup Request',
                'verbose_name_plural': 'ID Signup Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('issued_id', 'user')},
            },
        ),
    ]
