# Generated by Django 4.2.7 on 2025-10-26 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_contact_email_user_registration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminissuedid',
            name='assigned_name',
            field=models.CharField(blank=True, help_text='Full name of the person this ID is assigned to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='assigned_phone',
            field=models.CharField(blank=True, help_text='Phone number for verification', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this ID is active and can be used for registration'),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether admin has verified the account created with this ID'),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this ID assignment'),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminissuedid',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
