# Generated by Django 4.2.7 on 2025-10-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_adminissuedid_assigned_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminissuedid',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('volunteer', 'Volunteer'), ('judge', 'Judge')], max_length=20),
        ),
    ]
