# Generated by Django 4.2.7 on 2026-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_adminissuedid_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', help_text='Volunteer availability status for emergency assignments', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
