# Generated by Django 4.2.7 on 2026-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_temporary_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], max_length=10, null=True),
        ),
    ]
