# Generated by Django 4.2.7 on 2026-03-16 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventregistration_group_leader_name_and_more'),
        ('users', '0015_schoolparticipant_gender_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='School-assigned unique group ID', max_length=100)),
                ('group_class', models.CharField(choices=[('LP', 'Lower Primary'), ('UP', 'Upper Primary'), ('HS', 'High School'), ('HSS', 'Higher Secondary School')], max_length=10)),
                ('gender_category', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('MIXED', 'Mixed')], max_length=10)),
                ('participant_count', models.PositiveSmallIntegerField()),
                ('leader_full_name', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('bulk', 'Bulk Import')], default='manual', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(blank=True, related_name='school_group_entries', to='events.event')),
                ('leader_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_school_groups', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_school_group_entries', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(limit_choices_to={'role': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_group_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Group Entry',
                'verbose_name_plural': 'School Group Entries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_order', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_leader', models.BooleanField(default=False)),
                ('group_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.schoolgroupentry')),
            ],
            options={
                'verbose_name': 'School Group Member',
                'verbose_name_plural': 'School Group Members',
                'ordering': ['member_order'],
                'unique_together': {('group_entry', 'member_order')},
            },
        ),
        migrations.AddConstraint(
            model_name='schoolgroupentry',
            constraint=models.CheckConstraint(check=models.Q(('participant_count__gte', 1), ('participant_count__lte', 20)), name='school_group_participant_count_range'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolgroupentry',
            unique_together={('school', 'group_id')},
        ),
    ]
