# Generated by Django 4.2.7 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_schoolgroupentry_schoolgroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroupmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolgroupmember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='schoolgroupmember',
            name='student_class',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Class 1-12', null=True),
        ),
    ]
