# Generated by Django 4.2.7 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_schoolgroupmember_gender_student_class_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolgroupmember',
            constraint=models.CheckConstraint(
                check=models.Q(student_class__isnull=True) | (
                    models.Q(student_class__gte=1) & models.Q(student_class__lte=12)
                ),
                name='school_group_member_class_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='schoolgroupmember',
            constraint=models.CheckConstraint(
                check=models.Q(gender__isnull=True) | models.Q(gender__in=['BOYS', 'GIRLS']),
                name='school_group_member_gender_choices',
            ),
        ),
    ]
