# Generated by Django 4.2.7 on 2025-10-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('schedule', 'Schedule'), ('venue', 'Venue'), ('organization', 'Organization'), ('technical', 'Technical'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('event', 'Event Feedback'), ('system', 'System Feedback'), ('other', 'Other')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
