# Generated by Django 4.2.7 on 2026-01-08 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('LP', 'LP'), ('UP', 'UP'), ('HS', 'HS'), ('HSS', 'HSS')], default='HSS', max_length=3, verbose_name='Participant Category'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Certificate Number'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('merit', 'Merit Certificate'), ('participation', 'Participation Certificate')], default='participation', max_length=15, verbose_name='Certificate Type'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='district_name',
            field=models.CharField(default='', max_length=100, verbose_name='District Name'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='prize',
            field=models.CharField(blank=True, choices=[('1st', '1st Prize'), ('2nd', '2nd Prize'), ('3rd', '3rd Prize'), ('consolation', 'Consolation Prize'), ('participation', 'Participation')], max_length=15, null=True, verbose_name='Prize/Rank'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='school_name',
            field=models.CharField(default='', max_length=200, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
