# Generated by Django 4.2.7 on 2026-01-08 05:45

from django.db import migrations
import uuid


def populate_certificate_numbers(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    for cert in Certificate.objects.filter(certificate_number__isnull=True):
        cert.certificate_number = f'CERT-{cert.event.id}-{uuid.uuid4().hex[:8].upper()}'
        cert.save()


def reset_certificate_numbers(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    Certificate.objects.update(certificate_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_category_certificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_certificate_numbers,
            reverse_code=reset_certificate_numbers
        ),
    ]
