# Generated by Django 4.2.7 on 2026-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20260108_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Certificate Number'),
        ),
    ]
