# Generated by Django 4.2.7 on 2026-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_certificate_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Certificate Number'),
        ),
    ]
